# Generated by Django 3.2 on 2021-06-04 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('news', '0002_auto_20210604_0919'),
    ]

    operations = [
        migrations.CreateModel(
            name='news',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('author', models.CharField(max_length=100)),
                ('text', models.CharField(max_length=5000)),
                ('url', models.CharField(max_length=200)),
                ('pub_time', models.DateTimeField(verbose_name='published')),
            ],
        ),
    ]
